AWSTemplateFormatVersion: "2010-09-09"
Description: AWS IoT Analytics Sample

Parameters:
  NamePrefix:
    Type: String
  IoTCertificateName:
    Type: String

Resources:
  IoTPolicy:
    Type: AWS::IoT::Policy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "iot:*"
            Resource: "*"
      PolicyName: !Sub ${NamePrefix}-iot-policy
  IoTThing:
    Type: AWS::IoT::Thing
    Properties:
      ThingName: !Sub ${NamePrefix}-iot-thing
  IoTPolicyPrincipalAttachment:
    Type: AWS::IoT::PolicyPrincipalAttachment
    Properties:
      PolicyName: !Ref IoTPolicy
      Principal: !Sub arn:aws:iot:${AWS::Region}:${AWS::AccountId}:cert/${IoTCertificateName}
  IoTThingPrincipalAttachment:
    Type: AWS::IoT::ThingPrincipalAttachment
    Properties:
      ThingName: !Ref IoTThing
      Principal: !Sub arn:aws:iot:${AWS::Region}:${AWS::AccountId}:cert/${IoTCertificateName}
