AWSTemplateFormatVersion: "2010-09-09"
Description: AWS IoT Analytics Sample

Parameters:
  NamePrefix:
    Type: String
  IoTCertificateName:
    Type: String

Resources:
  IoTPolicy:
    Type: AWS::IoT::Policy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "iot:*"
            Resource: "*"
      PolicyName: !Sub ${NamePrefix}_iot_policy
  IoTThing:
    Type: AWS::IoT::Thing
    Properties:
      ThingName: !Sub ${NamePrefix}_iot_thing
  IoTPolicyPrincipalAttachment:
    Type: AWS::IoT::PolicyPrincipalAttachment
    Properties:
      PolicyName: !Ref IoTPolicy
      Principal: !Sub arn:aws:iot:${AWS::Region}:${AWS::AccountId}:cert/${IoTCertificateName}
  IoTThingPrincipalAttachment:
    Type: AWS::IoT::ThingPrincipalAttachment
    Properties:
      ThingName: !Ref IoTThing
      Principal: !Sub arn:aws:iot:${AWS::Region}:${AWS::AccountId}:cert/${IoTCertificateName}
  IoTAnalyticsChannel:
    Type: AWS::IoTAnalytics::Channel
    Properties:
      ChannelName: !Sub ${NamePrefix}_iot_analytics_channel
      ChannelStorage:
        ServiceManagedS3: {}
      RetentionPeriod:
        NumberOfDays: 1
        Unlimited: false
  IoTAnalyticsDatastore:
    Type: AWS::IoTAnalytics::Datastore
    Properties:
      DatastoreName: !Sub ${NamePrefix}_iot_analytics_datastore
      DatastoreStorage:
        ServiceManagedS3: {}
      RetentionPeriod:
        NumberOfDays: 1
        Unlimited: false
  IoTAnalyticsPipeline:
    Type: AWS::IoTAnalytics::Pipeline
    Properties:
      PipelineName: !Sub ${NamePrefix}_iot_analytics_pipeline
      PipelineActivities:
        - Channel:
            Name: pipeline_channel_activity
            ChannelName: !Sub ${NamePrefix}_iot_analytics_channel
            Next: pipeline_datastore_activity
          Datastore:
            Name: pipeline_datastore_activity
            DatastoreName: !Sub ${NamePrefix}_iot_analytics_datastore
  IoTAnalyticsDataset:
    Type: AWS::IoTAnalytics::Dataset
    Properties:
      DatasetName: !Sub ${NamePrefix}_iot_analytics_dataset
      Actions:
        - ActionName: SqlAction
          QueryAction:
            SqlQuery: !Sub "SELECT * FROM ${NamePrefix}_iot_analytics_datastore"
      RetentionPeriod:
        NumberOfDays: 1
        Unlimited: false
  IoTAnalyticsBatchPutMessageRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - iot.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: !Sub ${NamePrefix}_iot_analytics_topic_rule
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "iotanalytics:BatchPutMessage"
                Resource: "*"
  IoTTopicRule:
    Type: AWS::IoT::TopicRule
    Properties:
      RuleName: !Sub ${NamePrefix}_iot_topic_rule
      TopicRulePayload:
        Actions:
          - IotAnalytics:
              ChannelName: !Sub ${NamePrefix}_iot_analytics_channel
              RoleArn: !GetAtt IoTAnalyticsBatchPutMessageRole.Arn
        AwsIotSqlVersion: "2016-03-23"
        RuleDisabled: false
        Sql: "SELECT * FROM 'iot/topic'"
